install: Fix a few bugs in the default file setup
I kept getting errors because I made some stupid mistakes in my
previous commit:

Traceback (most recent call last):
  File "./install.py", line 325, in <module>
    sys.exit(main(sys.argv))
  File "./install.py", line 316, in main
    create_default_files()
  File "./install.py", line 174, in create_default_files
    setup_default_file(default, skip_if_exists=True)
  File "./install.py", line 82, in setup_default_file
    st = os.stat(target)
FileNotFoundError: [Errno 2] No such file or directory: '/home/philipp/.xprofile.local'